#!/bin/bash

params=""

if [ -n $params ]; then
   echo "Please enter number of script runs."
   echo "Usage : run-gpu.sh <count>"
   #exit
fi

for (( i=1; i<=$1; i++ ))
do
   echo "Run $i:"
   ./$2
done
